config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/about'

  root 'bras#index'
  resources :bras do
    resources :bra_sizes, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :tags, only: [:create, :destroy]
  resources :categories, only: [:index, :show]

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

end

app/models/bra.rb
class Bra < ActiveRecord::Base
  belongs_to :user
  has_many :bra_sizes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags

  def all_tags=(raw_tags)
    split_tags = raw_tags.split(", ")
    self.categories = self.categories + split_tags.map { |tag_name| Category.where(name: tag_name.strip).first_or_create! }
  end

end

app/controllers/bras_controller.rb
class BrasController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => [:index, :show]

  def index
    @non_tags = false
    @bras = Bra.all
    @index = true
    @bra_size = BraSize.new
    @tag = Tag.new
  end

  def new
    @bra = Bra.new
  end

  def create
    @bra = Bra.new(bra_params)
    @bra.user = current_user
    if @bra.save
      redirect_to bra_path(@bra)
    else
      render :new
    end
  end

  def show
    @non_tags = false
    @bra = Bra.find(params[:id])
    @bra_sizes = @bra.bra_sizes
    @review = Review.new
    @reviews = @bra.reviews
    @tag = Tag.new
  end

  def edit
    @bra = Bra.find(params[:id])
  end

  def update
    # This @non_tags variable is somewhat confusing for me, partially because
    # it's a variable named in the negative ('non_tags'), but also because it's
    # tied into your ability model as an instance variable, which increases the
    # implicit coupling between your controller and views (by that I mean you
    # have to rememeber to set this variable as true or false in every action
    # that renders a view that uses can? :update @bra)

    # Additonally, I'm fairly certain there's a permissions bug here that would
    # allow any user to update a bra they didn't create by injecting values
    # into params for this action. This is a subtle bug, but in short, I'd
    # suggest creating another action just for adding tags, and moving the
    # logic for creating tags into that controller action. I don't often
    # advocate for that, but in this case, you can handle authorization for
    # bra#update and tag#create completely independently. And the
    # tags_controller#create action can be more limited than this update action,
    # which allows updating of any bra attribute due to the un-limited
    # `@bra.update(bra_params)` line below.
    @non_tags = true
    @bra = Bra.find(params[:id])
    @bra.update(bra_params)
    redirect_to bra_path(@bra)
  end

  def destroy
    @bra = Bra.find(params[:id])
    @bra.destroy
    redirect_to bras_path
  end


private
def bra_params
  params.require(:bra).permit(:brand, :model, :image_url, :style, :all_tags)
end

end

app/views/bras/_bra.html.erb
<div class="bra clearfix">
  <img src="<%= bra.image_url %>">

  <div class="bra-info clearfix">
    <p>Brand: <%= bra.brand %></p>
    <p>Model: <%= bra.model %></p>
    <p>Style: <%= bra.style %></p>

    <div class="actions">
      <% if @index %>
        <li><%= link_to "Details and sizes", bra %></li>
      <% end %>
      <% if can? :delete, bra %>
      <li><%= link_to "Edit", edit_bra_path(bra) %></li>
      <li><%= link_to "Delete", bra_path(bra), method: 'delete' %></li>
      <% end %>
      <li><%= link_to "Add new size", new_bra_bra_size_path([bra, @bra_size]) %></li>
    </div>

    <div class="tags">
      <h4>Tags</h4>
      <% bra.tags.each do |tag| %>
        <span class="tag"><%= link_to tag.category.name, category_path(Category.find(tag.category_id)) %></span>
      <% end %>
      <div class="add-tag field">
        <%= form_for bra do |f| %>
          <%= f.text_field(:all_tags, value: nil)%>
          <%= f.submit "Add tag" %>
        <% end %>
      </div>
    </div>

  </div>

</div>

app/views/bras/_form.html.erb
<%= form_for @bra do |f| %>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :image_url%>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :all_tags %>
    <%= f.text_field(:all_tags, value: nil) %>
  </div>

  <%= f.submit %>

<% end %>

app/views/bras/index.html.erb
<%= render @bras %>

app/views/bras/new.html.erb
<%= render 'form' %>

app/views/bras/show.html.erb
<%= render @bra %>

<div class="data-points clearfix">
  <h3>Size data</h3>
  <%= render @bra_sizes %>
</div>

<div class="reviews clearfix">
  <h3>Reviews for <%= @bra.brand + ' ' + @bra.model %></h3>
  <%= render @reviews %>
  <%= render 'reviews/form' %>
</div>