config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/about'

  root 'bras#index'
  resources :bras do
    resources :bra_sizes, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :tags, only: [:create, :destroy]
  resources :categories, only: [:index, :show]

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource

  def new
    @bra = Bra.find(params[:bra_id])
    @review = Review.new
  end

  def create
    @bra = Bra.find(params[:bra_id])
    @review = Review.new(review_params)
    @review.bra = @bra
    @review.user = current_user
    if @review.save
      redirect_to bra_path(@bra)
    else
      redirect_to bra_path(@bra)
    end
  end

  def edit
    @bra = Bra.find(params[:bra_id])
    @review = Review.find(params[:id])
  end

  def update
    @bra = Bra.find(params[:bra_id])
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to bra_path(@bra)
  end

  def destroy
    @bra = Bra.find(params[:bra_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to bra_path(@bra)
  end

  private
  def review_params
    params.require(:review).permit(:author, :body)
  end

end

app/views/reviews/_form.html.erb
<%= form_for [@bra, @review] do |f| %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit %>

<% end %>

app/views/reviews/_review.html.erb
<div class="review">
  <p><%= review.author %> said: </p>
  <p><%= review.body %></p>
  <% if can? :edit, review %>
    <%= link_to "Edit review", edit_bra_review_path(@bra, review) %>
    <%= link_to "Delete review", bra_review_path(@bra, review), method: 'delete' %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<%= render 'form' %>