config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/about'

  root 'bras#index'
  resources :bras do
    resources :bra_sizes, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :tags, only: [:create, :destroy]
  resources :categories, only: [:index, :show]

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cupsofdata</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <img src="http://www.icon2s.com/wp-content/uploads/2013/07/black-white-metro-bra-icon.png">
  <%= link_to "Cups of data", bras_path %>
  <div class="user">
    <% if current_user %>
      <p>Signed in as <%= current_user.email %></p>
    <% end %>
  </div>
</header>

<nav>
  <li><%= link_to "About us", static_pages_about_path %></li>
  <li><%= link_to "See all bras", bras_path %></li>
  <li><%= link_to "Add new bra", new_bra_path %></li>
  <li><%= link_to "See categories", categories_path %></li>
  <% if current_user %>
    <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Sign in', sign_in_path %></li>
    <li><%= link_to "Sign up", new_user_path %></li>
  <% end %>
</nav>

<div class="notices">
  <% flash.each do |key, value| %>
  <div class="<%= key %>">
    <%= value %>
  </div>
  <% end %>
</div>

<div class="main clearfix">
<%= yield %>
</div>

</body>
</html>